# Docker Compose file for Vapor
#
# Install Docker on your system to run and test
# your Vapor app in a production-like environment.
#
# Note: This file is intended for testing and does not
# implement best practices for a production deployment.
#
# Learn more: https://docs.docker.com/compose/reference/
#
#   Build images: docker compose build
#      Start app: docker compose up app
#       Stop all: docker compose down
#

x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}

services:
  app:
    image: linkguard-api:latest
    build:
      context: .
    environment:
      <<: *shared_environment
    ports:
      - "8080:8080"
    # user: '0' # uncomment to run as root for testing purposes even though Dockerfile defines 'vapor' user.
    command:
      [
        "serve",
        "--env",
        "production",
        "--hostname",
        "0.0.0.0",
        "--port",
        "8080",
      ]
    depends_on:
      - mongo

  migrate:
    image: linkguard-api:latest
    build:
      context: .
    env_file:
      - .env.development
    environment:
      <<: *shared_environment
    env_file:
      - .env
    command: ["migrate", "--yes"]
    depends_on:
      - mongo

  revert:
    image: linkguard-api:latest
    build:
      context: .
    environment:
      <<: *shared_environment
    env_file:
      - .env
    command: ["revert", "--yes"]
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

# Additional services such as file-storage can be added here in the future.

#
# Volumes
volumes:
  mongo_data:
